# Generated by Django 2.2.3 on 2019-07-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20190707_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='languages',
        ),
        migrations.AlterField(
            model_name='language',
            name='paradigm',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Paradigm',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
